export const mockWeather_short = {
    "summary": "Cloudy",
    "precipType": "rain",
    "temperature": '3.17',
    "apparentTemperature": '2.79 °C',
    "pressure": '949.72 hPa',
    "windSpeed": '3.39 km/h',
}

export const mockWeather = {
  "latitude": -45.4,
  "longitude": -72.69,
  "timezone": "America/Santiago",
  "offset": -4,
  "currently": {
    "time": 1526364000,
    "summary": "Cloudy",
    "icon": "cloudy",
    "precipIntensity": 0,
    "precipType": "rain",
    "temperature": 3.17,
    "apparentTemperature": 2.79,
    "dewPoint": 2.03,
    "pressure": 949.72,
    "windSpeed": 3.39,
    "windBearing": 58.79,
    "cloudCover": 0
  },
  "hourly": {
    "data": [
      {
        "time": 1526356800,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.39,
        "precipType": "rain",
        "temperature": 3.65,
        "apparentTemperature": 3.07,
        "dewPoint": 2.18,
        "pressure": 948.41,
        "windSpeed": 3.85,
        "windBearing": 66.71,
        "cloudCover": 0
      },
      {
        "time": 1526360400,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.35,
        "precipType": "rain",
        "temperature": 3.22,
        "apparentTemperature": 2.64,
        "dewPoint": 2.05,
        "pressure": 948.94,
        "windSpeed": 3.77,
        "windBearing": 63.42,
        "cloudCover": 0
      },
      {
        "time": 1526364000,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.26,
        "precipType": "rain",
        "temperature": 3.17,
        "apparentTemperature": 2.79,
        "dewPoint": 2.03,
        "pressure": 949.72,
        "windSpeed": 3.39,
        "windBearing": 58.79,
        "cloudCover": 0
      },
      {
        "time": 1526367600,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.17,
        "precipType": "rain",
        "temperature": 3.08,
        "apparentTemperature": 2.79,
        "dewPoint": 1.94,
        "pressure": 949.56,
        "windSpeed": 3.23,
        "windBearing": 51.94,
        "cloudCover": 0
      },
      {
        "time": 1526371200,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.11,
        "precipType": "rain",
        "temperature": 3.21,
        "apparentTemperature": 3.08,
        "dewPoint": 2,
        "pressure": 950.06,
        "windSpeed": 3.01,
        "windBearing": 53.35,
        "cloudCover": 0
      },
      {
        "time": 1526374800,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.06,
        "precipType": "rain",
        "temperature": 3.12,
        "apparentTemperature": 3.22,
        "dewPoint": 2.03,
        "pressure": 950,
        "windSpeed": 2.65,
        "windBearing": 56.01,
        "cloudCover": 0
      },
      {
        "time": 1526378400,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.04,
        "precipType": "rain",
        "temperature": 2.8,
        "apparentTemperature": 2.54,
        "dewPoint": 1.65,
        "pressure": 950.61,
        "windSpeed": 3.14,
        "windBearing": 55.3,
        "cloudCover": 0
      },
      {
        "time": 1526382000,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.03,
        "precipType": "rain",
        "temperature": 2.37,
        "apparentTemperature": 2.65,
        "dewPoint": 1.52,
        "pressure": 951.19,
        "windSpeed": 2.32,
        "windBearing": 53.93,
        "cloudCover": 0
      },
      {
        "time": 1526385600,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.04,
        "precipType": "rain",
        "temperature": 2.74,
        "apparentTemperature": 2.89,
        "dewPoint": 1.86,
        "pressure": 951.28,
        "windSpeed": 2.54,
        "windBearing": 51.01,
        "cloudCover": 0
      },
      {
        "time": 1526389200,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0,
        "precipType": "none",
        "temperature": 3.69,
        "apparentTemperature": 3.46,
        "dewPoint": 2.87,
        "pressure": 951.76,
        "windSpeed": 3.24,
        "windBearing": 52.06,
        "cloudCover": 1
      },
      {
        "time": 1526392800,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.1,
        "precipType": "rain",
        "temperature": 4.55,
        "apparentTemperature": 4.93,
        "dewPoint": 2.73,
        "pressure": 952.35,
        "windSpeed": 2.42,
        "windBearing": 43.99,
        "cloudCover": 1
      },
      {
        "time": 1526396400,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.06,
        "precipType": "rain",
        "temperature": 5.52,
        "apparentTemperature": 6.26,
        "dewPoint": 3.29,
        "pressure": 952.45,
        "windSpeed": 2.04,
        "windBearing": 357.66,
        "cloudCover": 1
      },
      {
        "time": 1526400000,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.02,
        "precipType": "rain",
        "temperature": 6.66,
        "apparentTemperature": 7.39,
        "dewPoint": 3.27,
        "pressure": 952.66,
        "windSpeed": 2.16,
        "windBearing": 276.83,
        "cloudCover": 1
      },
      {
        "time": 1526403600,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0,
        "precipType": "rain",
        "temperature": 7.24,
        "apparentTemperature": 8.02,
        "dewPoint": 4.54,
        "pressure": 952.46,
        "windSpeed": 2.14,
        "windBearing": 270.09,
        "cloudCover": 1
      },
      {
        "time": 1526407200,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.01,
        "precipType": "rain",
        "temperature": 6.85,
        "apparentTemperature": 8.45,
        "dewPoint": 5.14,
        "pressure": 951.71,
        "windSpeed": 1.22,
        "windBearing": 261.54,
        "cloudCover": 1
      },
      {
        "time": 1526410800,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.01,
        "precipType": "rain",
        "temperature": 7.34,
        "apparentTemperature": 8.71,
        "dewPoint": 4.39,
        "pressure": 951.69,
        "windSpeed": 1.45,
        "windBearing": 226.76,
        "cloudCover": 1
      },
      {
        "time": 1526414400,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.01,
        "precipType": "rain",
        "temperature": 7.41,
        "apparentTemperature": 8.45,
        "dewPoint": 4.77,
        "pressure": 951.88,
        "windSpeed": 1.81,
        "windBearing": 205.28,
        "cloudCover": 0.92
      },
      {
        "time": 1526418000,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.01,
        "precipType": "rain",
        "temperature": 5.81,
        "apparentTemperature": 6.35,
        "dewPoint": 4.32,
        "pressure": 951.94,
        "windSpeed": 2.33,
        "windBearing": 186.97,
        "cloudCover": 0.18
      },
      {
        "time": 1526421600,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.02,
        "precipType": "rain",
        "temperature": 3.23,
        "apparentTemperature": 3.3,
        "dewPoint": 2.87,
        "pressure": 952.46,
        "windSpeed": 2.71,
        "windBearing": 155.1,
        "cloudCover": 0
      },
      {
        "time": 1526425200,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.15,
        "precipType": "rain",
        "temperature": 2.72,
        "apparentTemperature": 2.14,
        "dewPoint": 2.34,
        "pressure": 952.21,
        "windSpeed": 3.68,
        "windBearing": 127.24,
        "cloudCover": 0
      },
      {
        "time": 1526428800,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.14,
        "precipType": "rain",
        "temperature": 4.2,
        "apparentTemperature": 3.84,
        "dewPoint": 3.26,
        "pressure": 952.02,
        "windSpeed": 3.54,
        "windBearing": 116.19,
        "cloudCover": 0
      },
      {
        "time": 1526432400,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.06,
        "precipType": "rain",
        "temperature": 4.97,
        "apparentTemperature": 4.87,
        "dewPoint": 4.2,
        "pressure": 952.23,
        "windSpeed": 3.23,
        "windBearing": 95.87,
        "cloudCover": 0
      },
      {
        "time": 1526436000,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.05,
        "precipType": "rain",
        "temperature": 4.09,
        "apparentTemperature": 3.81,
        "dewPoint": 3.5,
        "pressure": 952.39,
        "windSpeed": 3.38,
        "windBearing": 93.58,
        "cloudCover": 0
      },
      {
        "time": 1526439600,
        "icon": "cloudy",
        "summary": "Cloudy",
        "precipAccumulation": 0.05,
        "precipType": "rain",
        "temperature": 4,
        "apparentTemperature": 3.65,
        "dewPoint": 3.64,
        "pressure": 952.07,
        "windSpeed": 3.51,
        "windBearing": 85.16,
        "cloudCover": 0
      }
    ]
  },
  "daily": {
    "data": [
      {
        "time": 1526356800,
        "icon": "rain",
        "summary": "Rain",
        "sunriseTime": 1526385806,
        "sunsetTime": 1526419822,
        "moonPhase": 0,
        "precipAccumulation": 0.21,
        "precipType": "rain",
        "temperatureHigh": 7.41,
        "temperatureHighTime": 1526414400,
        "temperatureLow": 2.37,
        "temperatureLowTime": 1526382000,
        "apparentTemperatureHigh": 8.71,
        "apparentTemperatureHighTime": 1526410800,
        "apparentTemperatureLow": 2.14,
        "apparentTemperatureLowTime": 1526425200,
        "dewPoint": 3.02,
        "pressure": 951.34,
        "windSpeed": 2.78,
        "windBearing": 127.7,
        "cloudCover": 0.34,
        "temperatureMin": 2.37,
        "temperatureMinTime": 1526382000,
        "temperatureMax": 7.41,
        "temperatureMaxTime": 1526414400,
        "apparentTemperatureMin": 2.14,
        "apparentTemperatureMinTime": 1526425200,
        "apparentTemperatureMax": 8.71,
        "apparentTemperatureMaxTime": 1526410800
      }
    ]
  }
}